name: DocC

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app
    runs-on: macos-15
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v4
        id: pages
      - name: Import Certs
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Setup Signing
        env:
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
        run: |
          echo "DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM" >> User.xcconfig
          echo "BUNDLE_ID_PREFIX = com.chimehq" >> User.xcconfig
      - name: Build DocC
        run: xcodebuild docbuild -scheme Edit -derivedDataPath /tmp/docbuild -destination 'generic/platform=macOS' | xcbeautify
      - name: Process Archive
        run: xcrun docc process-archive transform-for-static-hosting /tmp/docbuild/Build/Products/Debug/Chime.doccarchive --output-path docs --hosting-base-path 'Chime'
      - name: Add Redirect
        run: echo "<script>window.location.href += \"/documentation/chime\"</script>" > docs/index.html
      - name: Upload Docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
